db.orders.insertMany([
  {
    orderId: '1',
    subscriptionId: 'abc123',
    deliveryDate: '2017-05-02 00:13',
    paymentMethod: 'BKM',
    products: [{ product: '19 lt damanaca', quantity: 1 }],
    totalAmount: 10.0,
    status: 'NEW',
  },
  {
    orderId: '1',
    subscriptionId: 'abc123',
    deliveryDate: '2017-04-23 20:05',
    paymentMethod: 'MASTERPASS',
    products: [
      { product: '19 lt damanaca', quantity: 1 },
      { product: '10lt pet', quantity: 2 },
    ],
    totalAmount: 24.0,
    status: 'CONFIRMED',
  },
  {
    orderId: '3',
    subscriptionId: 'abc123',
    deliveryDate: '2017-03-31 16:35',
    paymentMethod: 'PAYATDOOR',
    products: [{ product: '19 lt damanaca', quantity: 2 }],
    totalAmount: 12.0,
    status: 'CANCELED',
  },
  {
    orderId: '4',
    subscriptionId: 'abc125',
    deliveryDate: '2017-03-29 11:19',
    paymentMethod: 'PAYATDOOR',
    products: [{ product: '19 lt damanaca', quantity: 3 }],
    totalAmount: 36.0,
    status: 'COMPLETED',
  },
  {
    orderId: '5',
    subscriptionId: 'abc125',
    deliveryDate: '2017-03-23 17:59',
    paymentMethod: 'BKM',
    products: [{ product: '5 lt pet', quantity: 2 }],
    totalAmount: 15.0,
    status: 'CONFIRMED',
  },
  {
    orderId: '6',
    subscriptionId: 'abc126',
    deliveryDate: '2017-03-09 19:02',
    paymentMethod: 'MASTERPASS',
    products: [
      { product: '19 lt damanaca', quantity: 1 },
      { product: '5 lt pet', quantity: 3 },
    ],
    totalAmount: 32.5,
    status: 'CANCELED',
  },
]);
